# Generated by Django 5.1.15 on 2026-05-20 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("up", "Thumbs up"), ("down", "Thumbs down")],
                        max_length=8,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rlhf_messag_user_id_43f56e_idx",
                    ),
                    models.Index(
                        fields=["rating"], name="rlhf_messag_rating_d61a85_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegenerationPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(help_text="The user prompt at this turn.")),
                (
                    "history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Conversation history up to (but not including) the rejected response.",
                    ),
                ),
                ("rejected_text", models.TextField()),
                (
                    "rejected_model_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("chosen_text", models.TextField()),
                (
                    "chosen_model_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_pairs",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regeneration_pairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regenerations",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rlhf_regene_user_id_2133d5_idx",
                    ),
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="rlhf_regene_convers_ac03ad_idx",
                    ),
                ],
            },
        ),
    ]
