# Generated by Django 5.1.15 on 2026-05-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_rename_accounts_gu_last_se_idx_accounts_gu_last_se_898896_idx_and_more",
        ),
        ("rlhf", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefeedback",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_feedback",
                to="accounts.guestvisitor",
            ),
        ),
        migrations.AddField(
            model_name="regenerationpair",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regeneration_pairs",
                to="accounts.guestvisitor",
            ),
        ),
        migrations.AlterField(
            model_name="messagefeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="regenerationpair",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regeneration_pairs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
