# Generated by Django 5.1.15 on 2026-05-24 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_guestvisitor"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="guestvisitor",
            new_name="accounts_gu_last_se_898896_idx",
            old_name="accounts_gu_last_se_idx",
        ),
        migrations.RenameIndex(
            model_name="guestvisitor",
            new_name="accounts_gu_country_8ad77f_idx",
            old_name="accounts_gu_country_idx",
        ),
    ]
