# Generated by Django 5.1.15 on 2026-05-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_key", models.CharField(max_length=64, unique=True)),
                ("rating", models.FloatField(default=1000.0)),
                ("battles", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("ties", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating"],
            },
        ),
        migrations.CreateModel(
            name="ArenaBattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_a_key", models.CharField(max_length=64)),
                ("model_b_key", models.CharField(max_length=64)),
                ("response_a", models.TextField(blank=True, default="")),
                ("response_b", models.TextField(blank=True, default="")),
                (
                    "vote",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a", "A is better"),
                            ("b", "B is better"),
                            ("tie", "Tie"),
                            ("both_bad", "Both bad"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arena_battles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="arena_arena_user_id_5c922c_idx",
                    )
                ],
            },
        ),
    ]
