# Generated by Django 5.1.15 on 2026-05-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_rename_accounts_gu_last_se_idx_accounts_gu_last_se_898896_idx_and_more",
        ),
        ("arena", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="arenabattle",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arena_battles",
                to="accounts.guestvisitor",
            ),
        ),
        migrations.AlterField(
            model_name="arenabattle",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arena_battles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="arenabattle",
            index=models.Index(
                fields=["guest", "-created_at"], name="arena_arena_guest_i_6a66bd_idx"
            ),
        ),
    ]
