from __future__ import annotations

from drf_spectacular.utils import OpenApiParameter
from rest_framework import serializers

from accounts.serializers import UserSerializer


VISITOR_ID_HEADER = OpenApiParameter(
    name="X-Visitor-Id",
    type=str,
    location=OpenApiParameter.HEADER,
    required=False,
    description=(
        "Persistent UUID generated by the client for guest/anonymous sessions. "
        "Mobile apps should create one UUID per install and send it on every "
        "request, even before login, so conversations and analytics stay linked."
    ),
)


class TokenPairSerializer(serializers.Serializer):
    access = serializers.CharField()
    refresh = serializers.CharField()


class AuthResponseSerializer(TokenPairSerializer):
    user = UserSerializer()


class TokenRefreshRequestSerializer(serializers.Serializer):
    refresh = serializers.CharField()


class TokenRefreshResponseSerializer(serializers.Serializer):
    access = serializers.CharField()


class HealthGpuSerializer(serializers.Serializer):
    nvidia_smi_available = serializers.BooleanField()
    gpu_name = serializers.CharField(allow_null=True)
    memory_total_mib = serializers.IntegerField(allow_null=True)
    memory_used_mib = serializers.IntegerField(allow_null=True)
    memory_free_mib = serializers.IntegerField(allow_null=True)
    torch_cuda_available = serializers.BooleanField()
    torch_cuda_error = serializers.CharField(allow_null=True)
    recommended_device = serializers.CharField()
    foreign_processes = serializers.ListField(child=serializers.JSONField())
    notes = serializers.ListField(child=serializers.CharField())
    inference_device = serializers.CharField()


class HealthResponseSerializer(serializers.Serializer):
    status = serializers.CharField()
    service = serializers.CharField()
    gpu = HealthGpuSerializer()
    loaded_model = serializers.CharField(allow_null=True)
    warning = serializers.CharField(required=False)


class ModelInfoSerializer(serializers.Serializer):
    key = serializers.CharField()
    label = serializers.CharField()
    description = serializers.CharField()
    family = serializers.CharField()


class ModelListResponseSerializer(serializers.Serializer):
    models = ModelInfoSerializer(many=True)
    default = serializers.CharField()
    current = serializers.CharField(allow_null=True)


class ConversationCreateRequestSerializer(serializers.Serializer):
    model_key = serializers.CharField(required=False)
    title = serializers.CharField(required=False, allow_blank=True)


class ConversationCompleteRequestSerializer(serializers.Serializer):
    content = serializers.CharField()
    model_key = serializers.CharField(required=False)


class ConversationRegenerateRequestSerializer(serializers.Serializer):
    model_key = serializers.CharField(required=False)


class ArenaBattleCreateRequestSerializer(serializers.Serializer):
    prompt = serializers.CharField()


class ArenaVoteRequestSerializer(serializers.Serializer):
    vote = serializers.ChoiceField(choices=("a", "b", "tie", "both_bad"))


class ArenaModelInfoSerializer(serializers.Serializer):
    key = serializers.CharField()
    label = serializers.CharField()


class ArenaRatingDeltaSerializer(serializers.Serializer):
    key = serializers.CharField()
    rating_before = serializers.FloatField()
    rating_after = serializers.FloatField()
    delta = serializers.FloatField()


class ArenaVoteResponseSerializer(serializers.Serializer):
    battle_id = serializers.IntegerField()
    vote = serializers.CharField()
    model_a = ArenaRatingDeltaSerializer()
    model_b = ArenaRatingDeltaSerializer()
    models = serializers.DictField(child=ArenaModelInfoSerializer())


class LeaderboardRowSerializer(serializers.Serializer):
    model_key = serializers.CharField()
    label = serializers.CharField()
    rating = serializers.FloatField()
    battles = serializers.IntegerField()
    wins = serializers.IntegerField()
    losses = serializers.IntegerField()
    ties = serializers.IntegerField()
    win_rate = serializers.FloatField()


class LeaderboardSnapshotSerializer(serializers.Serializer):
    version = serializers.IntegerField()
    total_battles = serializers.IntegerField()
    models = LeaderboardRowSerializer(many=True)

